// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_kol2cf_rev1.Context;

#nullable disable

namespace apbd_kol2cf_rev1.Migrations
{
    [DbContext(typeof(BoatServiceDbContext))]
    [Migration("20240609164028_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.BoatStandard", b =>
                {
                    b.Property<int>("IdBoatStandard")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdBoatStandard");

                    b.ToTable("BoatStandard", (string)null);
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdClientCategory")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdClient");

                    b.HasIndex("IdClientCategory");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.ClientCategory", b =>
                {
                    b.Property<int>("IdClientCategory")
                        .HasColumnType("int");

                    b.Property<int>("DiscountPerc")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdClientCategory");

                    b.ToTable("ClientCategory", (string)null);
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("datetime");

                    b.Property<bool>("Fullfilled")
                        .HasColumnType("bit");

                    b.Property<int>("IdBoatStandard")
                        .HasColumnType("int");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int>("NumOfBoats")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("money");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdBoatStandard");

                    b.HasIndex("IdClient");

                    b.ToTable("Reservation", (string)null);
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Sailboat", b =>
                {
                    b.Property<int>("IdSailboat")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdBoatStandard")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("IdSailboat");

                    b.HasIndex("IdBoatStandard");

                    b.ToTable("Sailboat", (string)null);
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.SailboatReservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .HasColumnType("int");

                    b.Property<int>("IdSailboat")
                        .HasColumnType("int");

                    b.HasKey("IdReservation", "IdSailboat");

                    b.HasIndex("IdSailboat");

                    b.ToTable("Sailboat_Reservation", (string)null);
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Client", b =>
                {
                    b.HasOne("apbd_kol2cf_rev1.Entities.ClientCategory", "ClientCategoryNavigation")
                        .WithMany("Clients")
                        .HasForeignKey("IdClientCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Client_ClientCategory");

                    b.Navigation("ClientCategoryNavigation");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Reservation", b =>
                {
                    b.HasOne("apbd_kol2cf_rev1.Entities.BoatStandard", "BoatStandardNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("IdBoatStandard")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("BoatStandard_Reservation");

                    b.HasOne("apbd_kol2cf_rev1.Entities.Client", "ClientNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Client_Reservation");

                    b.Navigation("BoatStandardNavigation");

                    b.Navigation("ClientNavigation");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Sailboat", b =>
                {
                    b.HasOne("apbd_kol2cf_rev1.Entities.BoatStandard", "BoatStandardNavigation")
                        .WithMany("Sailboats")
                        .HasForeignKey("IdBoatStandard")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Sailboat_BoatStandard");

                    b.Navigation("BoatStandardNavigation");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.SailboatReservation", b =>
                {
                    b.HasOne("apbd_kol2cf_rev1.Entities.Reservation", "ReservationNavigation")
                        .WithMany("SailboatReservations")
                        .HasForeignKey("IdReservation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Sailboat_Reservation_Reservation");

                    b.HasOne("apbd_kol2cf_rev1.Entities.Sailboat", "SailboatNavigation")
                        .WithMany("SailBoatReservations")
                        .HasForeignKey("IdSailboat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Sailboat_Reservation_Sailboat");

                    b.Navigation("ReservationNavigation");

                    b.Navigation("SailboatNavigation");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.BoatStandard", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Sailboats");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.ClientCategory", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Reservation", b =>
                {
                    b.Navigation("SailboatReservations");
                });

            modelBuilder.Entity("apbd_kol2cf_rev1.Entities.Sailboat", b =>
                {
                    b.Navigation("SailBoatReservations");
                });
#pragma warning restore 612, 618
        }
    }
}
